/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package javaavacado;

import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.sql.Connection;
import java.sql.Statement;
import javax.swing.JComboBox;
import javax.swing.JOptionPane;

/**
 *
 * @author H.Chirico
 */
public class NovoEstudante extends javax.swing.JFrame {

     private JComboBox firstComboBox;
     private JComboBox secondComboBox;
   
    public NovoEstudante() {
        initComponents();
         initCustomComponents();
          setResizable(false);
    }
    
    
    
     private void initCustomComponents() {
//    jComboBox2 = new JComboBox();
    
combo3.addItem("selecione o ano ");
combo3.addItem("1");
    combo3.addItem("2");
    combo3.addItem("3");
 combo3.addItem("4");

 
 
 
 

     combo1.addItem("Selecione a faculdade...");
    combo1.addItem("Faculdade de Ciencias e Tecnologia");
    combo1.addItem("Faculdade de Letras e Humanidade");
    combo1.addItem("Faculdade  de Educacao");
    combo1.addItem("Faculdade de  Economia e Gestao");
  
    
    combo1.addActionListener(new ActionListener() {
      public void actionPerformed(ActionEvent e) {
        String selectedItem = (String) combo1.getSelectedItem();
        if (selectedItem.equals("Selecione...")) {
          combo2.removeAllItems();
//          secondComboBox.addItem("");
        } else if (selectedItem.equals("Faculdade de Ciencias e Tecnologia")) {
          combo2.removeAllItems();
          combo2.addItem("Lic. Informática");
          combo2.addItem("Lic.Educação Visual");
           combo2.addItem("Lic. Eng. de Construção Civil");
            combo2.addItem("Lic. Geologia");
             combo2.addItem("Lic.Ensino de Química");
              combo2.addItem("Lic.Ensino de Física");
              combo2.addItem("Lic.Ensino de Matematica");
        
               combo2.addItem("Lic.Ensino de Biologia");
                combo2.addItem("Lic. Plan. e Ordenamento Territorial");
                 combo2.addItem("Lic. G. Ambiental e Desenvolvimento Comunitário");
                 
                  combo2.addItem("Lic.Estatística e Gestão de Informação");
                  
         
      
         
        }
        else if (selectedItem.equals("Faculdade de Letras e Humanidade")) {
          combo2.removeAllItems();
          combo2.addItem("lic. Direito");
          combo2.addItem("lic. Jornalismo");
          combo2.addItem("lic.Ciencias Politicas");
          combo2.addItem("lic. Sociologia");
          combo2.addItem("lic. Antropolia");
    
          
        }
        
        
        else if (selectedItem.equals("Faculdade  de Educacao")) {
          combo2.removeAllItems();
         
          combo2.addItem("lic. Ensino de Filosofia");
          combo2.addItem("lic.Ensino de Francês");
          combo2.addItem("lic. Ensino de Historia ");
          combo2.addItem("lic. Ensino de Inglês");
          combo2.addItem("lic. Ensino de Portugiês");
          combo2.addItem("lic. Gestão de Empresas");
           combo2.addItem("lic. Psicologia Educacional");
            combo2.addItem("lic. Psicologia Social");
             combo2.addItem("lic. Administracao e Gestao Educacional");
            combo2.addItem("lic. Ciencia de Educacao");
            combo2.addItem("lic. Educacao De Infancia");
            combo2.addItem("lic. Educacao fisica e Desporto");
          
        }
         else if (selectedItem.equals("Faculdade de  Economia e Gestao")) {
          combo2.removeAllItems();
          combo2.addItem("lic. Gestao Empresas");
          combo2.addItem("lic. Gestao de  Recursos Humano");
          combo2.addItem("lic.Contabilidade");
          
    
          
        }
        
        
        
        
        
      }
    });

    secondComboBox = new JComboBox();



    
      pack();
  }
    
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        combo1 = new javax.swing.JComboBox<>();
        combo2 = new javax.swing.JComboBox<>();
        combo3 = new javax.swing.JComboBox<>();
        nome = new javax.swing.JTextField();
        apelido = new javax.swing.JTextField();
        bi = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        ID = new javax.swing.JFormattedTextField();
        jLabel6 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Tela De cadastro de Estudante");
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Apelido");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 200, -1, -1));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Bilhete ID.");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 250, -1, -1));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Faculdade");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 300, -1, -1));

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Curso");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 360, -1, -1));

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Nome");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 120, -1, -1));

        jButton1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icones/save2.png"))); // NOI18N
        jButton1.setText("Salvar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 460, -1, 50));

        jButton2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icones/close2.png"))); // NOI18N
        jButton2.setText("Sair");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 460, -1, 50));

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Ano");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 410, -1, -1));

        combo1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        getContentPane().add(combo1, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 290, 360, 32));

        combo2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        getContentPane().add(combo2, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 350, 360, 33));

        combo3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        getContentPane().add(combo3, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 400, 360, 34));

        nome.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        getContentPane().add(nome, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 110, 360, 37));

        apelido.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        getContentPane().add(apelido, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 190, 360, 33));

        bi.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        getContentPane().add(bi, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 240, 360, 35));

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("ID Estudante ");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 50, -1, 30));

        try {
            ID.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##.####.####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        getContentPane().add(ID, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 60, 360, 30));

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icones/Licungo.jpg"))); // NOI18N
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        String IdEstudante=ID.getText();
        String Nome=nome.getText();
        String Apelido= apelido.getText();
        String Bi= bi.getText();
        String Faculdade=(String) combo1.getSelectedItem();
        String Curso= (String) combo2.getSelectedItem();
        int Ano=Integer.parseInt((String) combo3.getSelectedItem());
        
        try{
             Connection con= BD.getconnection();
             Statement st= con.createStatement();
             st.executeUpdate("insert into estudante values('"+IdEstudante+"','"+Nome+"','"+Apelido+"','"+Bi+"','"+ Faculdade+"','"+Curso+"', '"+Ano+"')");
             JOptionPane.showMessageDialog(null," Estudante Cadastrado com Sucesso");
             setVisible(true);
             new NovoEstudante().setVisible(true);
            
            
        }catch(Exception e){
            
           e.printStackTrace();
           
           JOptionPane.showMessageDialog(null," Id do estudante ja existe");
           
           setVisible(true);
             new NovoEstudante().setVisible(true);
        }
        
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        
        setVisible(false);
        new Home().setVisible(true);
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(NovoEstudante.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(NovoEstudante.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(NovoEstudante.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(NovoEstudante.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new NovoEstudante().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JFormattedTextField ID;
    private javax.swing.JTextField apelido;
    private javax.swing.JTextField bi;
    private javax.swing.JComboBox<String> combo1;
    private javax.swing.JComboBox<String> combo2;
    private javax.swing.JComboBox<String> combo3;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JTextField nome;
    // End of variables declaration//GEN-END:variables
}
